apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  suspend: true
  completions: 10
  parallelism: 4
  backoffLimit: 4
  activeDeadlineSeconds: 100
  ttlSecondsAfterFinished: 1500
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never


