apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default: # this section defines default limits
      cpu: 500m
      memory: 2Gi
    defaultRequest: # this section defines default requests
      cpu: 500m
      memory: 1Gi
    max: # max and min define the limit range
      cpu: "1"
      memory: 2Gi
    min:
      cpu: 100m
      momory: 1Gi
    type: Container

